### ISSUE TITLE
Replace default IP 127.0.0.1 with 0.0.0.0

### ISSUE THREAD

**Issue by zagovorichev** [brefphp/dev-server#1]
Why is the tool available on a fixed port?
https://github.com/brefphp/dev-server/blob/master/bin/bref-dev-server#L25

It would be much more convenient to use configurable values --host --port (and specify 0.0.0.0 for the default ip)

**Comment by hungvietdo** [comment]
Oh. I did not see this issue request earlier. But put in a pull request here.
https://github.com/brefphp/dev-server/pull/5/files

cc: @mnapoli

**Comment by zagovorichev** [comment]
fixed with 0.2.3
