### ISSUE TITLE
Compile on ARM64 as well as AMD64

### ISSUE THREAD

**Issue by shadowhand** [brefphp/dev-server#2]
Our company is switching over to Apple M1 laptops within the next couple of months and I noticed that the Bref Docker images are only available as `amd64` images.

Could we please get `arm64` in addition to `amd64` images? 🥺

**Comment by deleugpn** [comment]
I was working on support for arm64 but I got blocked by https://github.com/docker/compose/issues/8804 for now

**Comment by shadowhand** [comment]
This is on the wrong project, should be on brefphp/bref.
